name: First Actions
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello
      - name: Print 2  to console
        run: |
            echo Hello 2
        
